module.exports = {
  secure_channels: ['PGP', 'Signal', 'Off-the-Record Messaging (OTR)', 'Other'],
  services: [
    'Alerts and Warnings',
    'Incident Analysis',
    'Incident Response Support',
    'Incident Response Coordination',
    'Incident Response On Site',
    'Vulnerability Analysis',
    'Vulnerability Response',
    'Vulnerability Response Coordination',
    'Announcements',
    'Technology Watch',
    'Infrastructure Review',
    'Best-Practice Review',
    'Scanning',
    'Penetration Testing',
    'Configuration and Maintenance of Security',
    'Development of Security Tools',
    'Intrusion Detection Services',
    'Security-Related Information Dissemination',
    'Secure Hosting',
    'DOS-Protection Services',
    'Artifact Analysis',
    'Artifact Response',
    'Artifact Response Coordination',
    'Risk Analysis',
    'Business Continuity and Disaster Recovery',
    'Security Consulting',
    'Awareness-Building',
    'Education/Training',
    'Product Evaluation or Certification'
  ],
  statuses: ['unassigned', 'assigned', 'in-progress', 'resolved', 'reviewed'],
  incident_types: [
    'Account Compromise',
    'Denial-of-Service',
    'Destruction/Loss',
    'Disruption of Communications Applications and Platforms',
    'Information Leak',
    'Internet/Network Outage',
    'Intrusion Attempt',
    'Known Vulnerability',
    'Malfunction/Failure of Devices or Systems',
    'Malicious Website',
    'Malware',
    'Social Engineering',
    'Targeted Censorship',
    'Theft/Confiscation',
    'User-Device Compromise',
    'Website/Server Compromise'
  ],
  languages: [
    'Farsi',
    'English',
    'Arabic',
    'Azerbaijani',
    'Bengali',
    'Dutch',
    'French',
    'German',
    'Hindi',
    'Italian',
    'Japanese',
    'Javanese',
    'Kurdish',
    'Malay',
    'Mandarin Chinese',
    'Portuguese',
    'Punjabi',
    'Russian',
    'Spanish',
    'Swahili',
    'Tamil',
    'Telugu',
    'Urdu',
    'Other'
  ],
  types_of_work: [
    'Anti-Corruption and Transparency',
    'Anti-War/Anti-Violence',
    'Culture',
    'Economic Change',
    'Education',
    'Election Monitoring',
    'Environment',
    'Freedom of Expression',
    'Freedom Tool Development',
    'Funding',
    'Health Issues',
    'Human Rights Issues',
    'Internet and Telecoms',
    'LGBT/Gender/Sexuality',
    'Policy',
    'Politics',
    'Privacy',
    'Rapid Response',
    'Refugees',
    'Security',
    "Women's Rights",
    'Youth Rights'
  ],
  per_week_availability: [
    'less than an hour a week',
    '2-4 hours a week',
    '5-10 hours a week',
    '10-20 hours a week',
    'more than 20 hours a week'
  ],
  start_time: [
    'within hours',
    'within days',
    'within a week',
    'within weeks',
    'not accepting new cases'
  ],
  notification_prefs: ['Guidance', 'Alerts', 'Incident Notifications'],
  notification_languages: ['English', 'Farsi']
};
